//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidId { get; set; }
        public int UserId { get; set; }
        public int JobId { get; set; }
        public Nullable<bool> Status { get; set; }
        public int EmployerId { get; set; }
    }
}
