//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal InitialBudget { get; set; }
        public decimal finalBudget { get; set; }
        public bool Java { get; set; }
        public bool Javascript { get; set; }
        public bool C { get; set; }
        public bool Csharp { get; set; }
        public bool Cplus { get; set; }
        public bool PHP { get; set; }
        public bool Objective_C { get; set; }
        public bool Python { get; set; }
        public bool ASP_NET { get; set; }
        public bool Ruby { get; set; }
        public bool SQL { get; set; }
        public bool Html { get; set; }
        public bool Css { get; set; }
        public bool Android { get; set; }
        public bool XML { get; set; }
        public string Category { get; set; }
        public string Other { get; set; }
        public string Date { get; set; }
        public bool Status { get; set; }
        public bool Request { get; set; }
    }
}
