//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotiId { get; set; }
        public int EmployerId { get; set; }
        public int FreelancerId { get; set; }
        public string EmployerMsg { get; set; }
        public string FreelancerMsg { get; set; }
        public bool Status { get; set; }
        public bool Read { get; set; }
        public int JobId { get; set; }
        public string Date { get; set; }
        public string Type { get; set; }
    }
}
