//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string UserType { get; set; }
        public string CompanyName { get; set; }
        public string About_Yourself { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Status { get; set; }
        public string HideText { get; set; }
        public string PicName { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public bool Java { get; set; }
        public bool Javascript { get; set; }
        public bool C { get; set; }
        public bool Csharp { get; set; }
        public bool Cplus { get; set; }
        public bool PHP { get; set; }
        public bool Objective_C { get; set; }
        public bool Python { get; set; }
        public bool ASP_NET { get; set; }
        public bool Ruby { get; set; }
        public bool SQL { get; set; }
        public bool Html { get; set; }
        public bool Css { get; set; }
        public bool Android { get; set; }
        public bool XML { get; set; }
        public string Others { get; set; }
        public bool WebDeveloper { get; set; }
        public bool Tester { get; set; }
        public bool MobileDeveloper { get; set; }
        public bool SystemDesign { get; set; }
        public bool SystemAnalyst { get; set; }
        public bool ProjectManager { get; set; }
        public bool GameDeveloper { get; set; }
        public bool Marketing { get; set; }
        public bool OthersJob { get; set; }
    }
}
