//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public int EmployerId { get; set; }
        public int FreelancerId { get; set; }
        public string EmployerName { get; set; }
        public string FreelancerName { get; set; }
        public int JobId { get; set; }
        public bool CheckConfirm { get; set; }
        public Nullable<int> Path { get; set; }
    }
}
